apiVersion: v1
kind: PersistentVolume
metadata:
  name: sqlite-pv
  labels:
    type: sqlite
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/storefront/sqlite
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  labels:
    type: uploads
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/storefront/uploads
